// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnb9r4rZce5PzCDrW_bXFkUeXBbvc6xtU',
    appId: '1:861708455158:web:ee6a6c43c13ad209cfb0d7',
    messagingSenderId: '861708455158',
    projectId: 'delay-detective',
    authDomain: 'delay-detective.firebaseapp.com',
    storageBucket: 'delay-detective.firebasestorage.app',
    measurementId: 'G-0BG7JVD3QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHwxDNYHf61SG7NjtwMoDkyBD-9BcISk',
    appId: '1:861708455158:android:3d8c3b74a4dd73b5cfb0d7',
    messagingSenderId: '861708455158',
    projectId: 'delay-detective',
    storageBucket: 'delay-detective.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltbicIML_tGgq1fOspYzxSA-TSx92Rwo',
    appId: '1:861708455158:ios:73f2cc948a1dbe29cfb0d7',
    messagingSenderId: '861708455158',
    projectId: 'delay-detective',
    storageBucket: 'delay-detective.firebasestorage.app',
    iosBundleId: 'com.hyeji.delayDetective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCltbicIML_tGgq1fOspYzxSA-TSx92Rwo',
    appId: '1:861708455158:ios:73f2cc948a1dbe29cfb0d7',
    messagingSenderId: '861708455158',
    projectId: 'delay-detective',
    storageBucket: 'delay-detective.firebasestorage.app',
    iosBundleId: 'com.hyeji.delayDetective',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnb9r4rZce5PzCDrW_bXFkUeXBbvc6xtU',
    appId: '1:861708455158:web:2dea68800790e480cfb0d7',
    messagingSenderId: '861708455158',
    projectId: 'delay-detective',
    authDomain: 'delay-detective.firebaseapp.com',
    storageBucket: 'delay-detective.firebasestorage.app',
    measurementId: 'G-BMSZBFVCJP',
  );
}
